# Generated by Django 5.2.7 on 2025-10-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('size', models.IntegerField(help_text='m²')),
                ('image', models.ImageField(upload_to='properties/')),
                ('property_type', models.CharField(choices=[('Sale', 'Shitje'), ('Rent', 'Qira')], default='Sale', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
