# Generated by Django 5.2.7 on 2025-10-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentProperty',
            fields=[
            ],
            options={
                'verbose_name': 'Property for Rent',
                'verbose_name_plural': 'Properties for Rent',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('RealEstate.property',),
        ),
        migrations.CreateModel(
            name='SaleProperty',
            fields=[
            ],
            options={
                'verbose_name': 'Property for Sale',
                'verbose_name_plural': 'Properties for Sale',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('RealEstate.property',),
        ),
        migrations.RemoveField(
            model_name='property',
            name='created_at',
        ),
        migrations.AddField(
            model_name='property',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.IntegerField(),
        ),
    ]
