# Generated by Django 5.2.7 on 2025-10-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0002_rentproperty_saleproperty_remove_property_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent'), ('home', 'home')], max_length=10),
        ),
    ]
