# Generated by Django 5.2.7 on 2025-10-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0003_alter_property_property_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='show_on_home',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Sale', 'Shitje'), ('Rent', 'Qira')], max_length=10),
        ),
    ]
