# Generated by Django 5.2.7 on 2025-10-14 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0004_remove_property_show_on_home_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rooms',
        ),
        migrations.RemoveField(
            model_name='property',
            name='size',
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='RealEstate.property')),
            ],
        ),
    ]
